NetCoreProject/Pages/Users/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NetCoreProject.Data;
using NetCoreProject.Models;

namespace NetCoreProject.Pages.Users
{
    public class EditModel : PageModel
    {
        private ApplicationDbContext _db;

        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ApplicationUser ApplicationUser { get; set; }
        public async Task OnGet(string id)
        {
            ApplicationUser = await _db.ApplicationUser.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var user = await _db.ApplicationUser.FindAsync(ApplicationUser.Id);
                user.Name = ApplicationUser.Name;
                user.Email= ApplicationUser.Email;
                user.PhoneNumber = ApplicationUser.PhoneNumber;
                user.Address = ApplicationUser.Address;
                user.City = ApplicationUser.City;
                user.PostalCode = ApplicationUser.PostalCode;

                await _db.SaveChangesAsync();
                return RedirectToPage("Index");

            }
            return RedirectToPage();
        }
    }
}

NetCoreProject/Pages/Users/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NetCoreProject.Data;
using NetCoreProject.Models;

namespace NetCoreProject.Pages.Users
{
    [Authorize(Roles = "Admin")]
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public List<ApplicationUser> ApplicationUserList { get; set; }
        public async Task<IActionResult> OnGet()
        {
            ApplicationUserList = await _db.ApplicationUser.ToListAsync();
            return Page();
        }
        public async Task<IActionResult> OnPostDelete(string id)
        {
            var applicationUser = await _db.ApplicationUser.FindAsync(id);
            if (applicationUser == null)
            {
                return NotFound();

            }
            _db.ApplicationUser.Remove(applicationUser);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");
        }

    }
}

NetCoreProject/Pages/Users/Edit.cshtml
@page
@model NetCoreProject.Pages.Users.EditModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<br />
<h2 class="text-info">Edit User</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="ApplicationUser.Id"></label>
            </div>
            <div class="col-6">
                <input asp-for="ApplicationUser.Id" class="form-control" readonly="readonly" />
                <span asp-validation-for="ApplicationUser.Id" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="ApplicationUser.Name"></label>
            </div>
            <div class="col-6">
                <input asp-for="ApplicationUser.Name" class="form-control" />
                <span asp-validation-for="ApplicationUser.Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-4">
                <label asp-for="ApplicationUser.Email"></label>
            </div>
            <div class="col-6">
                <input asp-for="ApplicationUser.Email" class="form-control" />
                <span asp-validation-for="ApplicationUser.Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-4">
                <label asp-for="ApplicationUser.PhoneNumber"></label>
            </div>
            <div class="col-6">
                <input asp-for="ApplicationUser.PhoneNumber" class="form-control" />
                <span asp-validation-for="ApplicationUser.PhoneNumber" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-4">
                <label asp-for="ApplicationUser.Address"></label>
            </div>
            <div class="col-6">
                <input asp-for="ApplicationUser.Address" class="form-control" />
                <span asp-validation-for="ApplicationUser.Address" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-4">
                <label asp-for="ApplicationUser.City"></label>
            </div>
            <div class="col-6">
                <input asp-for="ApplicationUser.City" class="form-control" />
                <span asp-validation-for="ApplicationUser.City" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-4">
                <label asp-for="ApplicationUser.PostalCode"></label>
            </div>
            <div class="col-6">
                <input asp-for="ApplicationUser.PostalCode" class="form-control" />
                <span asp-validation-for="ApplicationUser.PostalCode" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3 offset-4">
                <input type="submit" value="Update" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div> 

NetCoreProject/Pages/Users/Index.cshtml
@page
@model NetCoreProject.Pages.Users.IndexModel
@{
    ViewData["Title"] = "Index"; 
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<form method="post">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info">Users List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-page="/Account/Register" asp-area="Identity" class="btn btn-info">
                <i class="fas fa-plus"></i>  Create New User
            </a>
        </div>
    </div>

    <div class="border bg-white">
        <br />
        <div>
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        @Html.DisplayNameFor(m => m.ApplicationUserList[0].Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.ApplicationUserList[0].PhoneNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.ApplicationUserList[0].Email)
                    </th>
                    <th>
                      
                    </th>
                </tr>
                @foreach (var item in Model.ApplicationUserList)
                {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(m => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Email)
                </td>
                <td>

                            <a class="btn btn-primary text-white" asp-page="Edit" asp-route-id="@item.Id">
                                <i class="fas fa-edit">Edit</i>
                            </a>
                            <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-danger text-white">
                                <i class="fas fa-edit">Delete</i>
                            </button>
                        


                </td>
            </tr>

                }
            </table>
        </div>
    </div>
</form>  